# SPDX-License-Identifier: MIT
# Copyright (c) 2019 Gennady Trafimenkov
---

- name: Add key
  apt_key: url=https://www.aptly.info/pubkey.txt id=ED75B5A4483DA07C state=present
  become: yes

- name: Add repository
  apt_repository: repo="deb http://repo.aptly.info/ squeeze main" state=present update_cache=yes
  become: yes
