# SPDX-License-Identifier: MIT
# Copyright (c) 2019 Gennady Trafimenkov
---

- name: Create folder
  file: path=/opt/vpn-simple-server state=directory
  become: yes

- name: Copy scripts
  template: src={{item}} dest=/opt/vpn-simple-server/{{item}} mode=0755
  with_items:
    - generate-client-cert.sh
    - init.sh
    - start.sh
  become: yes

- name: Copy files
  template: src={{item}} dest=/opt/vpn-simple-server/{{item}} mode=0644
  with_items:
    - readme.md
  become: yes
