# SPDX-License-Identifier: MIT
# Copyright (c) 2019 Gennady Trafimenkov
---

- name: Add https://packages.cloud.google.com/apt/doc/apt-key.gpg
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes
